"""The fixed, public PR-label taxonomy (GitHub colors omit the leading #)."""

LABELS: dict[str, dict[str, str]] = {
    "type: bug": {"color": "d73a4a", "description": "Fixes incorrect or broken behavior."},
    "type: feature": {"color": "a2eeef", "description": "Adds a new user-facing capability."},
    "type: refactor": {"color": "c5def5", "description": "Restructures code without intentionally changing behavior."},
    "type: docs": {"color": "0075ca", "description": "Changes documentation or explanatory examples."},
    "type: performance": {"color": "fbca04", "description": "Improves runtime performance or resource efficiency."},
    "type: maintenance": {"color": "ededed", "description": "Upkeep, dependencies, build tooling, CI or repository automation, not user runtime features."},
    "area: tui": {"color": "5319e7", "description": "Terminal user interface and interactive terminal behavior."},
    "area: providers": {"color": "5319e7", "description": "Model providers, routing, authentication, or provider protocols."},
    "area: tools": {"color": "5319e7", "description": "Agent tool implementations and tool execution."},
    "area: swarm": {"color": "5319e7", "description": "Multi-agent coordination and swarm workflows."},
    "area: config": {"color": "5319e7", "description": "Configuration loading, settings, and preferences."},
    "area: install": {"color": "5319e7", "description": "Installation, distribution, packaging, and updates."},
    "area: ci": {"color": "5319e7", "description": "Continuous integration and automated repository workflows."},
    "area: desktop": {"color": "5319e7", "description": "Desktop application and native desktop integration."},
    "platform: windows": {"color": "bfdadc", "description": "Windows-specific behavior, support, or compatibility."},
    "platform: macos": {"color": "bfdadc", "description": "macOS-specific behavior, support, or compatibility."},
    "platform: linux": {"color": "bfdadc", "description": "Linux-specific behavior, support, or compatibility."},
    "breaking-change": {"color": "b60205", "description": "Incompatible public behavior or interface change requiring migration."},
    "security": {"color": "b60205", "description": "Security-sensitive change or vulnerability remediation."},
    "needs-tests": {"color": "e4e669", "description": "Manual review indicates additional tests are needed."},
    "blocked": {"color": "e4e669", "description": "Manually identified dependency or workflow blocker."},
    "size: XS": {"color": "c2e0c6", "description": "Trivial change such as a typo, requiring no design and no runtime or CI policy change."},
    "size: S": {"color": "a2eeef", "description": "Focused change within one component or one existing workflow, even when calling an external service."},
    "size: M": {"color": "0075ca", "description": "Substantive change to a subsystem or related components."},
    "size: L": {"color": "d876e3", "description": "Change spanning cross-subsystem interfaces or behavior."},
    "size: XL": {"color": "b60205", "description": "Architectural change or substantial migration."},
}
